source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

def swift3_overrides
    pod 'SnapKit',  :git => 'https://github.com/SnapKit/SnapKit.git',       :branch => 'feature/0.40.0'
end

target 'BMPlayer_Example' do
    swift3_overrides
    pod 'BMPlayer', :path => '../'
end


post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '3.0'
        end
    end
end
